### PR TITLE
 [JENKINS-65161] remove commons-digester2 from core and upgrade plugins to commons-digester3

### PR DESCRIPTION
**Pull request by olamy**

### CODE REVIEW

**Comment by olamy** [comment]
see https://github.com/jenkinsci/jenkins/pull/5320

**Review by rsandell — APPROVED** [review]

**Comment by rsandell** [comment]
I reran the build to make it succeed as it looked like an environmental issue.

**Review by alecharp — APPROVED** [review]

**Review by MRamonLeon — APPROVED** [review]

**Comment by alecharp** [comment]
@jlamasrios do you think this PR could be merged and you could cut a release of the plugin with it? Thanks.

**Comment by batmat** [comment]
Hi @jlamasrios, FYI we are about to merge the Core PR that relates to this change. 

Without merging & releasing with this current PR, this plugin will be **broken** in the first weekly shipped with the core change.

Thanks!

**Comment by jlamasrios** [comment]
Hi, thanks for the PR and sincere apologies for the delay!

I'll look into it to merge it asap.

**Review by jlamasrios — APPROVED** [review]

**Comment by jlamasrios** [comment]
Hi,

Sincere apologies for the delay. I've already merged the PR and done a new
release (1.10)

Thanks!

**Pull request merged**
